tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#8990a8",
        "tertiary": "#bec6e0",
        "on-tertiary": "#283044",
        "secondary-fixed-dim": "#b7c8e1",
        "surface": "#101415",
        "on-secondary-container": "#a9bad3",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-lowest": "#0b0f10",
        "on-error-container": "#ffdad6",
        "primary-container": "#4d8eff",
        "surface-dim": "#101415",
        "outline-variant": "#424754",
        "on-tertiary-fixed": "#131b2e",
        "primary": "#adc6ff",
        "inverse-primary": "#005ac2",
        "error": "#ffb4ab",
        "secondary": "#b7c8e1",
        "on-primary": "#002e6a",
        "on-secondary-fixed-variant": "#38485d",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-fixed-variant": "#3f465c",
        "error-container": "#93000a",
        "on-error": "#690005",
        "primary-fixed-dim": "#adc6ff",
        "background": "#101415",
        "surface-container": "#1d2022",
        "tertiary-fixed": "#dae2fd",
        "secondary-fixed": "#d3e4fe",
        "surface-variant": "#323537",
        "on-surface": "#e0e3e5",
        "on-tertiary-container": "#22293d",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-container-high": "#272a2c",
        "on-background": "#e0e3e5",
        "on-primary-fixed": "#001a42",
        "on-primary-container": "#00285d",
        "surface-container-low": "#191c1e",
        "inverse-on-surface": "#2d3133",
        "on-primary-fixed-variant": "#004395",
        "secondary-container": "#3a4a5f",
        "on-secondary": "#213145",
        "outline": "#8c909f",
        "surface-container-highest": "#323537",
        "surface-bright": "#363a3b",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#adc6ff",
        "inverse-surface": "#e0e3e5"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "unit": "6px",
        "stack-lg": "20px",
        "section-padding": "56px",
        "stack-sm": "6px",
        "stack-md": "10px",
        "container-max-width": "1200px",
        "gutter": "16px"
      },
      "fontFamily": {
        "headline-xl": ["Geist"],
        "label-md": ["Geist"],
        "headline-md": ["Geist"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Geist"],
        "headline-xl-mobile": ["Geist"],
        "headline-lg": ["Geist"]
      },
      "fontSize": {
        "headline-xl": ["36px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-md": ["18px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["13px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["22px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-xl-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-lg": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
}
